config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs do
    member do
      get :confirm
    end
  end

  namespace :admin do
      resources :users
      resources :admin_users
      resources :posts
      resources :audit_logs

      root to: "users#index"
    end

  resources :posts do
    member do
      get :approve
    end
  end
  
  devise_for :users, skip: [:registrations]

  root to: 'static#homepage'
end

app/views/shared/_nav.html.erb
<div class="logo">
	<h1>Time Tracker</h1>
</div>

<ul class="custom-nav nav nav-tabs">
	<li class="<%= active?(root_path) %> nav-item">
		<%= link_to "Home", root_path %>
	</li>
	<li class="<%= active?(posts_path) %> nav-item">
		<%= link_to "Time Entries", posts_path %>
	</li>
	<li class="<%= active?(new_post_path) %> nav-item">
		<%= link_to "New Entry", new_post_path, id: 'new_post_from_nav' %>
	</li>
	<li class="<%= active?(admin_posts_path) %> nav-item">
		<a class="nav-link disabled" href="#">Messages</a>
	</li>
	<% if current_user %>
	<li class="<%= active?(audit_logs_path) %> nav-item">
		<% if current_user.type == 'AdminUser' %>
			<%= link_to "Audit Log", audit_logs_path %>
		<% end %>
	</li>
	<li class="nav-item dropdown ml-md-auto pull-right d-flex">
		<div class="dropdown">
		  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
		    <li><a class="dropdown-item" href="#">Action</a></li>
		    <li><a class="dropdown-item" href="#">Another action</a></li>
		    <li><a class="dropdown-item" href="#">Something else here</a></li>
		  </ul>
		</div>
		<div class="dropdown dropdown-toggle">
			<% if current_user.type == 'AdminUser' %>
				<%= link_to "Admin Dashboard", admin_posts_path %>
			<% end %>
			<%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
		 <a class="nav-item dropdown dropdown-toggle d-flex flex-column" 
		 data-toggle="dropdown d-flex flex-column"
		 >TODO: Dropdown</a>
		<div class="dropdown-menu dropdown-menu-right" 
			aria-labelledby="navbarDropdownMenuLink">
			<%= link_to "admin dash", root_path %>
			<%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
			 <a class="dropdown-item" href="#">Something else here</a>
			<div class="dropdown-divider">
			</div> <a class="dropdown-item" href="#">Separated link</a>
		</div>
	</li>
</ul>
<% end %>